# $Id$

# THIS IS A TEMPLATE

CC = vc
SHCC = true
AR = vlink
AR_ARGS = -r -o \$$@
RANLIB = true
STDC99 = -c99
PIC =
LIB_PREFIX =
LIB_SUFFIX = .dll
EXEC_SUFFIX = .$(VBCC_PLATFORM)
STATICLIB_PREFIX =
STATICLIB_SUFFIX = .a
PLATFORM_M = $(VBCC_PLATFORM)
PLATFORM_P = $(VBCC_PLATFORM)
CFLAGS += +$(VBCC_PLATFORM) -DNO_STRDUP -DNO_UNISTD -Doff_t=int64_t
DFLAGS += +$(VBCC_PLATFORM) -DNO_STRDUP -DNO_UNISTD -Doff_t=int64_t
LDFLAGS += +$(VBCC_PLATFORM)
