CC = WATCOM=$$WATCOM INCLUDE=$$WATCOM/h PATH=$$PATH:$$WATCOM/binl64 owcc
SHCC = /bin/true
AR = WATCOM=$$WATCOM INCLUDE=$$WATCOM/h PATH=$$PATH:$$WATCOM/binl64 wlib
AR_ARGS = -b -n -fag -o=\$$@
RANLIB = /bin/true
LIB_PREFIX =
LIB_SUFFIX = .dll
EXEC_SUFFIX = .$(WATCOM_PLATFORM)
STATICLIB_PREFIX =
STATICLIB_SUFFIX = .a
PLATFORM_M = $(WATCOM_PLATFORM)
PLATFORM_P = $(WATCOM_PLATFORM)
CFLAGS += -DDOS -b $(WATCOM_PLATFORM)
LDFLAGS += -b $(WATCOM_PLATFORM)
LINK_LIB = `find Library -name "*.o"`
