name: Build DataWorks

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        save-always: true
        path: /var/cache/apt
        key: pkgcache-${{ github.sha }}
        restore-keys: pkgcache-
    - name: Install packages
      run: sudo apt-get install zip byacc flex doxygen mingw-w64 graphviz
    - name: make sure it is clean (linux64)
      run: make clean
    - name: make for linux64
      run: make YACC=byacc -j3 archive
    - name: rename to -linux64
      run: mv dataworks.tar.gz dataworks-linux64.tar.gz
    - name: make sure it is clean (win32)
      run: make clean
    - name: make for win32
      run: make YACC=byacc PLATFORM=win32 -j3 archive
    - name: rename to -win32
      run: mv dataworks.tar.gz dataworks-win32.tar.gz
    - name: make sure it is clean (win64)
      run: make clean
    - name: make for win64
      run: make YACC=byacc PLATFORM=win64 -j3 archive
    - name: rename to -win64
      run: mv dataworks.tar.gz dataworks-win64.tar.gz
    - name: release
      run: gh release create -t "Release $(date +"%a %b %e %H:%M:%S %Z %Y")" "$(date +%Y%m%d%H%M%S)" dataworks-linux64.tar.gz dataworks-win32.tar.gz dataworks-win64.tar.gz --generate-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
