name: Build DataWorks

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install zip byacc flex doxygen
    - name: make
      run: make YACC=byacc archive
    - name: rename
      run: mv dataworks.zip dataworks-linux64.zip && mv dataworks.tar.gz dataworks-linux64.tar.gz
    - name: release
      run: gh release create -t "Release $(date +"%a %b %e %H:%M:%S %Z %Y")" dataworks-linux64.tar.gz --generate-notes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
