name: Deploy pages

on:
  workflow_dispatch:
  push:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-pages:

    name: "Deploy pages"

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install doxygen graphviz
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: "Document/doc/html"
    - name: Deploy
      uses: actions/deploy-pages@v4
