name: Deploy pages

on:
  workflow_dispatch:
  push:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-pages:

    name: "Deploy pages"

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install doxygen graphviz
    - name: Setup directories
      run: mkdir -p pages/en && mkdir -p pages/jp
    - name: Make HTML
      run: echo "<html><head><meta charset=\"UTF-8\"><title>Select</title></head><body><h1>Select</h1><hr><ul><li><a href=\"./en\">English</a></li><li><a href=\"./jp\">Japanese</a></li></ul></body></html>" > pages/index.html
    - name: Clean
      run: make clean
    - name: Make
      run: make ./Document
    - name: Copy files
      run: cp -rf Document/doc/html/* pages/en/
    - name: Clean
      run: make clean
    - name: Make
      run: make ./Document DOCTARGET=document-jp
    - name: Copy files
      run: cp -rf Document/doc/htmljp/* pages/jp/
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: "pages"
    - name: Deploy
      uses: actions/deploy-pages@v4
